name: Build Docs and Open PR
on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Python Docs
      uses: jbheard/markdown-docs@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Open docs update PR
      uses: ad-m/github-push-action@master
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
