# This is a basic workflow to help you get started with Actions

name: Email & Whatsapp Notification

# Run when a tag is created 
on:
  push:
    tags:
      - '*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME}}
          password: ${{ secrets.MAIL_PASSWORD}}
          subject: Release notification
          body: ${{github.repository}} has a new release
          to: ict.eti.consultants@gmail.com
          from: RatVenture notifications
          cc: dhkua60@gmail.com, quekdylan7@gmail.com
          content_type: text/html
          convert_markdown: true

      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
          to_whatsapp_no: ${{ secrets.to_whatsapp_no }}

        uses: ishween/whatsapp-push-notify-action@0ebd035b3d88b770a573a6d87f54860043ac0165
